Repository prgrms-fe-devcourse/NFE1-1-3-broken-handle-truck-Frontend, pull requests merged in 2024-10, with the labels that each got.

#2 setting: svg 파일 삭제
  public/vite.svg
  src/assets/react.svg
Labels: design

#8 setting: 라우터 설정
  src/App.tsx
  src/pages/BookMarkPage.tsx
  src/pages/DetailPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/MapPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: setting

#11 setting: Tailwind 구성파일에 색상코드 및 포인트 폰트 추가
  src/index.css
  tailwind.config.js
Labels: setting

#13 fix: 오타 수정
  tailwind.config.js
Labels: fix

#16 setting: SVGR 플러그인 설치 및 사용을 위한 svg 코드 변경
  package-lock.json
  package.json
  src/assets/images/category.svg
  src/assets/images/map.svg
  src/assets/images/star.svg
  src/assets/images/user.svg
  vite.config.ts
Labels: setting

#19 design: card 컴포넌트 퍼플리싱
  src/components/Card.tsx
Labels: design

#18 design: BookMarkButton 컴포넌트 퍼블리싱
  src/components/BookMarkButton.tsx
Labels: design

#20 design: select component 퍼블리싱
  src/components/Select.tsx
  tailwind.config.js
Labels: design

#22 setting: vite-plugin-svgr 설정
  src/vite-env.d.ts
Labels: setting

#25 setting: TailwindCSS colors 추가
  tailwind.config.js
Labels: setting

#28 fix: Main, Login, SignUp 페이지가 RootLayout 적용되도록 수정
  src/App.tsx
Labels: fix

#30 design: BoomMarkButton 수정
  src/assets/images/star.svg
  src/components/BookMarkButton.tsx
Labels: design

#31 design: Card 컴포넌트 수정
  src/assets/images/defaultMenu.svg
  src/components/Card.tsx
Labels: design

#33 [design] 공통 레이아웃 컴포넌트 퍼블리싱
  src/assets/images/leftArrow.svg
  src/layouts/BottomNavBar.tsx
  src/layouts/TopBar.tsx
  src/layouts/layout.tsx
Labels: design

#35 design: Comment 컴포넌트 퍼블리싱
  src/assets/images/delete.svg
  src/components/Comment.tsx
Labels: design

#36 [Design] NoReview 컴포넌트 퍼블리싱
  src/assets/images/messageSquare.svg
  src/components/NoReview.tsx
Labels: design

#39 design: SignUpInput 컴포넌트 퍼블리싱
  src/components/SignUpInput.tsx
Labels: design

#43 design: Toggle 컴포넌트 퍼블리싱
  src/components/Toggle.tsx
Labels: design

#45 fix: SignUpInput Props 타입 수정
  src/components/SignUpInput.tsx
Labels: fix

#49 design: Category 컴포넌트 퍼블리싱
  package-lock.json
  package.json
  src/components/Category.tsx
  src/index.css
  src/layouts/BottomNavBar.tsx
Labels: design

#47 fix: SignUpInput을 Input 컴포넌트로 변경
  src/components/Input.tsx
Labels: fix

#48 design: button 컴포넌트 퍼블리싱
  src/components/Select.tsx
  src/components/button.tsx
Labels: design

#54 design: 컴포넌트 fontSize 수정
  src/components/Card.tsx
  src/components/Comment.tsx
  src/components/Menu.tsx
Labels: design

#57 design: 컴포넌트 폰트 사이즈 수정
  src/components/Input.tsx
  src/components/Toggle.tsx
  src/layouts/BottomNavBar.tsx
  src/layouts/TopBar.tsx
Labels: design

#61 design: 메인 페이지 퍼블리싱
  src/pages/MainPage.tsx
Labels: design

#63 feat: zustand로 title 전역관리 및 topbar 수정
  src/layouts/TopBar.tsx
  src/layouts/layout.tsx
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
  src/store/titleStore.ts
Labels: feat

#65 design: 로그인 페이지 퍼블리싱
  src/pages/LoginPage.tsx
Labels: design

#67 design: 회원가입 페이지 퍼블리싱
  src/assets/images/check.svg
  src/pages/SignUpPage.tsx
Labels: design

#69 design: 내 가게 페이지 퍼블리싱
  src/components/Comment.tsx
  src/components/NoReview.tsx
  src/layouts/TopBar.tsx
  src/pages/owner/MyTruckPage.tsx
  tailwind.config.js
Labels: design

#71 design: 카테고리 리스트 퍼블리싱
  src/components/Category.tsx
  src/layouts/BottomNavBar.tsx
  src/layouts/layout.tsx
Labels: design

#73 feat: Navigate에 Fade 적용하는 함수 분리
  src/hooks/useFadeNavigate.ts
Labels: feat

#76 fix: To 타입을 string | number로 수정
  src/hooks/useFadeNavigate.ts
Labels: fix

#77 fix: 화면 변환 로직 수정
  src/components/Category.tsx
  src/layouts/BottomNavBar.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
Labels: fix

#79 setting: 카테고리 리스트
  src/assets/images/category/category-1.svg
  src/assets/images/category/category-10.svg
  src/assets/images/category/category-11.svg
  src/assets/images/category/category-12.svg
  src/assets/images/category/category-13.svg
  src/assets/images/category/category-2.svg
  src/assets/images/category/category-3.svg
  src/assets/images/category/category-4.svg
  src/assets/images/category/category-5.svg
  src/assets/images/category/category-6.svg
  src/assets/images/category/category-7.svg
  src/assets/images/category/category-8.svg
  src/assets/images/category/category-9.svg
  src/constants/categories.ts
  src/types/category.ts
Labels: setting

#81 design: 가게 등록 페이지 퍼블리싱
  src/components/Input.tsx
  src/components/Select.tsx
  src/components/button.tsx
  src/layouts/TopBar.tsx
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: design

#82 fix: Category 컴포넌트에서 사용하는 데이터 변경
  src/components/Category.tsx
Labels: fix

#85 fix: 가게 등록 페이지에서 BottomNavBar 안보이게 수정
  src/layouts/layout.tsx
Labels: fix

#86 design 지도 페이지 퍼블리싱
  index.html
  package-lock.json
  package.json
  src/assets/images/locationIcon.svg
  src/assets/images/searchIcon.svg
  src/components/Card.tsx
  src/components/Toggle.tsx
  src/components/map/MyLocation.tsx
  src/components/map/Search.tsx
  src/hooks/useMyLocation.ts
  src/hooks/useSearch.ts
  src/hooks/useToggle.ts
  src/mocks/truckDatas.json
  src/pages/MapPage.tsx
  tsconfig.json
Labels: design, feat

#89 fix: 계란빵 이미지 변경
  src/assets/images/category/category-12.svg
Labels: fix

#91 fix: Select 컴포넌트 수정
  src/components/Select.tsx
Labels: fix

#92 design: 가게 상세 정보 페이지 퍼블리싱
  src/assets/images/lock.svg
  src/components/WriteReview.tsx
  src/index.css
  src/pages/DetailPage.tsx
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
  tailwind.config.js
Labels: design

#95 fix: logo 추가 및 경로 수정
  src/assets/images/pinkLogo.svg
  src/pages/owner/MyTruckPage.tsx
Labels: fix

#96 design: ui 수정
  src/components/map/MyLocation.tsx
  src/components/map/Search.tsx
  src/pages/MainPage.tsx
  src/pages/MapPage.tsx
Labels: design

#98 fix: 카테고리 위치 이상 수정
  src/index.css
  src/layouts/BottomNavBar.tsx
Labels: fix

#103 design: 메인/로그인/회원가입 페이지 추가 퍼블리싱
  src/assets/images/kakao.svg
  src/index.css
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUpPage.tsx
  tailwind.config.js
Labels: design

#106 fix: BottomNavBar 모든 메뉴 나오게 수정
  src/layouts/BottomNavBar.tsx
Labels: fix

#109 design: ui 수정
  src/components/Card.tsx
  src/pages/BookMarkPage.tsx
Labels: design

#105 design: detail, register 페이지 지도 추가
  src/pages/DetailPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: design

#111 fix: 로그인 / 회원가입 페이지 수정
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: design, fix

#112 design: ui 수정
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: design

#114 design: 메인 / 로그인 / 회원가입 페이지 수정
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUpPage.tsx
  tailwind.config.js
Labels: design, fix

#116 setting: axios instance
  src/apis/apiClient.ts
Labels: setting

#120 feat: Store API 연동
  src/apis/store/deleteStoreApi.ts
  src/apis/store/getMyStoreApi.ts
  src/apis/store/getStoreApi.ts
  src/apis/store/getStoreListApi.ts
  src/apis/store/postStoreApi.ts
  src/types/store.ts
Labels: feat

#122 setting: api client 수정
  src/apis/apiClient.ts
Labels: setting

#129 setting: 기본 Response 타입 정의 및 데이터 항상 반환되도록 변경
  src/apis/apiClient.ts
  src/types/response.d.ts
Labels: setting

#130 feat: 가게 API 연동
  src/apis/store.ts
  src/apis/store/deleteStoreApi.ts
  src/apis/store/getMyStoreApi.ts
  src/apis/store/getStoreApi.ts
  src/apis/store/getStoreListApi.ts
  src/apis/store/postStoreApi.ts
  src/types/store.d.ts
Labels: feat

#135 setting: 카테고리 리스트 저장 방식 수정 및 map marker 이미지 추가
  src/assets/images/category/index.ts
  src/assets/images/category/marker-1.svg
  src/assets/images/category/marker-10.svg
  src/assets/images/category/marker-11.svg
  src/assets/images/category/marker-12.svg
  src/assets/images/category/marker-13.svg
  src/assets/images/category/marker-2.svg
  src/assets/images/category/marker-3.svg
  src/assets/images/category/marker-4.svg
  src/assets/images/category/marker-5.svg
  src/assets/images/category/marker-6.svg
  src/assets/images/category/marker-7.svg
  src/assets/images/category/marker-8.svg
  src/assets/images/category/marker-9.svg
  src/assets/images/category/marker-default.svg
  src/components/Category.tsx
  src/components/Select.tsx
  src/constants/categories.ts
Labels: setting, fix

#136 feat: Bookmark API 연동
  src/apis/bookmark.ts
  src/types/bookmark.d.ts
Labels: feat

#139 fix: 오타 수정
  src/assets/images/category/index.ts
Labels: fix

#138 feat: 카카오로그인 제외 auth api 구현
  src/apis/apiClient.ts
  src/apis/auth.ts
  src/components/Input.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/types/auth.d.ts
Labels: feat

#143 feat: Map 페이지 추가 퍼블리싱 및 StoreList 보여주기
  src/assets/reload.svg
  src/components/map/MapMarker.tsx
  src/constants/categories.ts
  src/pages/MapPage.tsx
Labels: design, feat

#145 [design] 알림 페이지 퍼블리싱 및 북마크 ui 수정
  src/App.tsx
  src/apis/auth.ts
  src/assets/images/noti.svg
  src/assets/images/pinkNoti.svg
  src/components/Message.tsx
  src/components/bookmark/NoBookMark.tsx
  src/layouts/TopBar.tsx
  src/layouts/layout.tsx
  src/pages/BookMarkPage.tsx
  src/pages/NotificationPage.tsx
  src/pages/owner/MyTruckPage.tsx
Labels: design

#147 feat: Detail 페이지 path 변경
  src/App.tsx
  src/components/Card.tsx
  src/layouts/TopBar.tsx
  src/layouts/layout.tsx
  src/pages/MapPage.tsx
Labels: feat

#150 fix: Store API에 commentCount 추가되면서 수정되어야하는 부분 수정
  src/pages/MapPage.tsx
  src/types/store.d.ts
Labels: fix

#151 design: Card 컴포넌트 수정
  src/components/Card.tsx
  src/pages/MapPage.tsx
Labels: design
