Repository prgrms-fe-devcourse/NFE1-1-3-broken-handle-truck-Frontend, pull requests merged in 2024-11, with the labels that each got.

#155 Feat: Notification API 연동
  src/apis/notification.ts
  src/types/notification.d.ts
Labels: feat

#156 feat: Detail 페이지 API 연동
  src/components/Card.tsx
  src/components/Comment.tsx
  src/pages/DetailPage.tsx
  src/types/comment.d.ts
  src/types/store.d.ts
Labels: design, feat

#159 setting: route, nav, layout 수정
  src/App.tsx
  src/assets/images/bell.svg
  src/layouts/BottomNavBar.tsx
  src/layouts/TopBar.tsx
  src/layouts/layout.tsx
  src/pages/MyPage.tsx
Labels: setting, fix

#160 feat: 사용자 인증확인 컴포넌트 구현
  src/apis/auth.ts
  src/components/routeGuards/AuthGuard.tsx
  src/components/routeGuards/MainGuard.tsx
  src/components/routeGuards/RoleGuard.tsx
  src/hooks/useAuthValidation.ts
  src/pages/LoginPage.tsx
  src/store/userStore.ts
  src/types/auth.d.ts
Labels: feat, fix

#165 design: my-truck 수정
  src/assets/images/leftArrow.svg
  src/assets/images/reload.svg
  src/components/EditStore.tsx
  src/components/button.tsx
  src/components/map/Search.tsx
  src/layouts/TopBar.tsx
  src/pages/MapPage.tsx
  src/pages/owner/MyTruckPage.tsx
Labels: design, refactor

#164 design: 마이페이지 퍼블리싱
  src/assets/images/edit2.svg
  src/assets/images/pinkLogo.svg
  src/components/NoReview.tsx
  src/pages/MyPage.tsx
  tailwind.config.js
Labels: design

#168 feat: 로그아웃 api 연동
  src/apis/auth.ts
  src/assets/images/truck.svg
  src/pages/MyPage.tsx
Labels: design, feat

#170 feat: 카테고리 / 검색 기능 구현
  src/apis/store.ts
  src/components/Category.tsx
  src/components/Menu.tsx
  src/hooks/useFetchStores.ts
  src/hooks/useSearch.ts
  src/layouts/BottomNavBar.tsx
  src/pages/MapPage.tsx
  src/store/storesStore.ts
  src/types/store.d.ts
Labels: feat

#167 feat: 트럭 등록 api 연동
  index.html
  src/components/Input.tsx
  src/components/Select.tsx
  src/components/Toggle.tsx
  src/components/button.tsx
  src/components/register/InputSection.tsx
  src/components/register/RegisterButton.tsx
  src/pages/owner/RegisterPage.tsx
Labels: feat

#174 fix: Map Toggle에 setValue 추가 및 빌드 오류 수정
  src/components/Input.tsx
  src/components/button.tsx
  src/mocks/myBookMark.json
  src/pages/MapPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: fix

#175 feat: toast message 적용
  package-lock.json
  package.json
  src/App.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/store/userStore.ts
Labels: feat

#178 design: 바텀시트 / BottomNavBar z-index 수정
  src/index.css
  src/layouts/BottomNavBar.tsx
Labels: design, fix

#184 feat: 탈퇴하기 구현, 로그아웃 수정, toast 추가
  src/apis/apiClient.ts
  src/apis/auth.ts
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/SignUpPage.tsx
Labels: feat

#185 feat: 내 가게 들어갔을 때 가게 있으면 조건부 처리
  src/apis/apiClient.ts
  src/components/EditStore.tsx
  src/components/Select.tsx
  src/components/button.tsx
  src/components/register/InputSection.tsx
  src/components/register/RegisterButton.tsx
  src/hooks/useMyStore.ts
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: feat

#187 feat: Notification 페이지 연동 및 소켓 관련 구현
  src/apis/notification.ts
  src/components/Message.tsx
  src/components/routeGuards/AuthGuard.tsx
  src/components/routeGuards/MainGuard.tsx
  src/pages/MyPage.tsx
  src/pages/NotificationPage.tsx
  src/store/notificationStore.ts
  src/store/userStore.ts
  src/types/notification.d.ts
Labels: feat, fix

#188 refactor: 로그아웃/탈퇴 후 카테고리 초기화 및 웹소켓 닫기
  src/pages/MyPage.tsx
Labels: refactor

#190 feat: 가게 등록 페이지 toast 추가
  src/components/EditStore.tsx
  src/components/register/RegisterButton.tsx
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: feat

#192 design: 새로운 알림 있을 때 동그라미 추가
  src/layouts/BottomNavBar.tsx
Labels: design

#193 design: map 반응형 수정
  src/components/Card.tsx
  src/components/map/Search.tsx
  src/pages/MapPage.tsx
Labels: design

#196 fix: MyTruck 수정
  src/pages/owner/MyTruckPage.tsx
Labels: fix

#200 feat: 마이페이지 API 연동
  src/apis/auth.ts
  src/apis/comment.ts
  src/components/Comment.tsx
  src/pages/DetailPage.tsx
  src/pages/MyPage.tsx
  src/pages/owner/MyTruckPage.tsx
  src/types/auth.d.ts
  src/types/comment.d.ts
Labels: feat

#199 design: 알림 페이지 반응형 수정
  src/components/Card.tsx
  src/components/Message.tsx
  src/layouts/BottomNavBar.tsx
  src/pages/NotificationPage.tsx
Labels: design

#204 design: map, my-truck, register 컴포넌트 등 반응형 수정
  src/components/Card.tsx
  src/components/Input.tsx
  src/components/Select.tsx
  src/components/register/InputSection.tsx
  src/components/register/RegisterButton.tsx
  src/layouts/TopBar.tsx
  src/pages/MapPage.tsx
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: design

#205 feat: 댓글 작성 / 삭제 연동 및 Detail페이지 수정
  src/apis/comment.ts
  src/components/Comment.tsx
  src/components/WriteReview.tsx
  src/hooks/useComment.ts
  src/pages/DetailPage.tsx
Labels: feat

#207 fix: MyTruck Title 오류 수정 및 Comment 컴포넌트 수정
  src/components/Comment.tsx
  src/pages/owner/MyTruckPage.tsx
Labels: fix

#209 design: 상세 페이지 반응형 수정
  src/assets/images/edit.svg
  src/components/WriteReview.tsx
  src/pages/DetailPage.tsx
  src/pages/NotificationPage.tsx
Labels: design, refactor

#211 fix: navigate replace 제거
  src/components/EditStore.tsx
Labels: fix

#213 fix: MyTruck 페이지 comment 개수 출력
  src/pages/owner/MyTruckPage.tsx
Labels: fix

#214 feat: useToggle API 연동 로직 구현 및 routeGuards 전면 수정
  src/App.tsx
  src/components/routeGuards/AuthGuard.tsx
  src/components/routeGuards/MainGuard.tsx
  src/components/routeGuards/PublicGuard.tsx
  src/hooks/useAuthValidation.ts
  src/hooks/useToggle.ts
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/NotificationPage.tsx
  src/store/notificationStore.ts
Labels: feat, setting, fix

#218 feat: 카카오 로그인 링크 추가
  src/pages/LoginPage.tsx
Labels: feat

#219 feat: 마이페이지 수정
  src/components/Loading.tsx
  src/pages/MyPage.tsx
Labels: feat

#221 fix: 상세 페이지 수정
  src/pages/DetailPage.tsx
Labels: fix

#225 fix: 에러메세지 위치 수정
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: fix

#224 fix: 카테고리키면 navbar도 클릭이 안되던 오류 수정
  src/index.css
Labels: fix

#230 fix: toggle 전체적으로 수정
  src/App.tsx
  src/components/Toggle.tsx
  src/hooks/useToggle.ts
  src/pages/MapPage.tsx
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: fix

#231 fix: 맵 => 상세 => 맵으로 돌아왔을 때 위치 수정
  src/pages/MapPage.tsx
  src/store/mapLocationStore.ts
Labels: fix

#229 [feat] 북마크 api 연동
  src/components/Card.tsx
  src/pages/BookMarkPage.tsx
  src/pages/MapPage.tsx
Labels: feat

#232 fix: RegisterPage 뒤로가기 제거 후 취소 버튼 추가
  src/components/EditStore.tsx
  src/components/register/RegisterButton.tsx
  src/layouts/TopBar.tsx
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: fix

#236 refactor: IUser 타입 thumnail 추가
  src/types/auth.d.ts
Labels: refactor

#235 feat: card, toggle 연동
  src/components/Card.tsx
  src/pages/BookMarkPage.tsx
  src/pages/MapPage.tsx
Labels: feat

#238 design: bookmark 반응형 수정
  src/components/bookmark/NoBookMark.tsx
  src/pages/BookMarkPage.tsx
Labels: design

#239 fix: TobBar z-index & 내 가게 페이지 버튼 수정
  src/components/EditStore.tsx
  src/layouts/TopBar.tsx
Labels: design, fix

#243 [desogn] 북마크 토스트 메뉴 띄우기
  src/components/Card.tsx
  src/hooks/useToggle.ts
Labels: design

#244 design: 카카오 프로필 추가(추후 수정..)
  src/pages/MyPage.tsx
Labels: design

#245 feat: UserStore 수정
  src/components/EditStore.tsx
  src/components/register/RegisterButton.tsx
  src/store/userStore.ts
Labels: feat

#247 feat: 닉네임 변경 로직 추가
  src/pages/MyPage.tsx
Labels: feat

#251 fix: toggle 조건 삭제
  src/hooks/useToggle.ts
Labels: fix

#252 fix: 배포시 소켓 연결 오류 수정
  src/store/notificationStore.ts
Labels: fix

#254 fix: Card 컴포넌트 수정 및 isOpen 변경될 때 데이터 가져오기
  src/components/Card.tsx
  src/hooks/useFetchStores.ts
  src/pages/BookMarkPage.tsx
  src/pages/MapPage.tsx
Labels: fix

#255 fix: 배포시 Socket 연결주소 오류 수정
  src/store/notificationStore.ts
Labels: fix

#263 design: WriteRview, MyTruckPage, DetailPage, RegisterPage 디자인 수정
  src/components/WriteReview.tsx
  src/index.css
  src/pages/DetailPage.tsx
  src/pages/owner/MyTruckPage.tsx
  src/pages/owner/RegisterPage.tsx
Labels: design

#261 feat: 검색 기능 수정
  src/assets/images/searchCancel.svg
  src/components/map/Search.tsx
  src/hooks/useSearch.ts
Labels: feat, docs

#260 refactor: 북마크 로직 분리 및 오류 수정
  src/components/BookMarkButton.tsx
  src/components/Card.tsx
  src/hooks/useFetchBookmark.ts
  src/hooks/useFetchStores.ts
  src/layouts/TopBar.tsx
  src/pages/BookMarkPage.tsx
  src/pages/MapPage.tsx
  src/types/bookmark.d.ts
Labels: fix, refactor

#259 feat: 로그인 엔터 이벤트 추가
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
Labels: feat

#264 refactor: routeGuards 화면 전환시 페이드 효과 삭제
  src/components/routeGuards/AuthGuard.tsx
  src/components/routeGuards/MainGuard.tsx
  src/components/routeGuards/PublicGuard.tsx
Labels: refactor

#268 feat: 상세페이지에 주소 추가
  src/pages/DetailPage.tsx
Labels: feat

#270 refactor: main, login, signup 디자인 약간 수정
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUpPage.tsx
Labels: design, refactor

#272 fix: Category 스크롤 수정
  src/components/Category.tsx
  src/index.css
Labels: design, fix

#278 fix: Category에 전체 추가
  src/assets/images/defaultMenu.svg
  src/assets/images/orangeLogo.svg
  src/components/Category.tsx
Labels: design, fix

#277 fix: search placeholder 문구 수정
  src/components/map/Search.tsx
Labels: fix

#284 setting: README 수정
  README.md
Labels: setting

#283 fix: 북마크 오류 수정
  src/components/BookMarkButton.tsx
Labels: fix

#285 fix: Mypage의 리뷰 컴포넌트 수정(상세 페이지 이동)
  src/components/Comment.tsx
  src/pages/MyPage.tsx
Labels: fix

#286 fix: 빌드시 타입 오류 수정
  src/components/Comment.tsx
Labels: fix

#288 fix: 상세페이지에서 다시 지도로 넘어갈 때 어색하던 부분 수정
  src/hooks/useFetchStores.ts
  src/pages/MapPage.tsx
  src/store/mapLocationStore.ts
Labels: fix

#290 fix: 지도 검색 결과 초기화
  src/hooks/useSearch.ts
Labels: fix
